### ISSUE TITLE
"attempt to index global 'BigWigs' (a nil value)" for every raid / encounter when attempting to access "Bosses" tab

### ISSUE THREAD

**Issue by tordenflesk** [monopsony/ElWigo#1]
https://i.imgur.com/DqLh37x.png

**Comment by monopsony** [comment]
Should be "fixed" in the newest update. The options table was never meant to be opened through the blizzard interface, I just forgot to remove that option back when I redesigned the interface.

I cant add it to the blizzard interface options as currently the options are being embedded in a frame that tracks whether the options are opened/closed (used to e.g. make all bars visible while options are opened), which doesn't work inside of the blizzard interface the way I've set it up.
