### ISSUE TITLE
Feature request: able to change font

### ISSUE THREAD

**Issue by OleBueker** [monopsony/ElWigo#2]
Currently, the font can't be changed inside the options, only the position, size and color. Please let us change fonts

**Comment by monopsony** [comment]
Hey, maybe I'm misunderstanding something but the font can be changed here: https://i.imgur.com/mFUymfk.png 

If your window looks different and is missing that option, I'll look into it

**Comment by OleBueker** [comment]
Strange, mine looks like this: [link](https://imgur.com/a/abulFzJ)
I'm on version 1.2.5-release

**Comment by monopsony** [comment]
Oooh you meant change the fonts of the bar ticks? I'll add that in the next update; the screenshot I showed was for the icons, not the bar ticks.

**Comment by monopsony** [comment]
The option to change the tick font was now added
