### ISSUE TITLE
TBC-specific release

### ISSUE THREAD

**Issue by vendethiel** [monopsony/ElWigo#4]
Hi,

Is there any plan to tag a release for TBC?

Thanks

**Comment by monopsony** [comment]
Hey,

Due to a somewhat recent BigWigs change, I would/will need to rewrite a significant portion of my code to keep ElWigo up to date. I am not yet sure how easy it'll be or if it's even doable at all without essentially rewriting the addon as a whole. If it is doable and I find the time, I'll also tag a release for TBC . In principle, the TBC code should be 99% the same, although I'll be unable to test it in raids myself (as I currently have no sub, nor do I have raid-ready characters on classic anyways).

**Comment by vendethiel** [comment]
Thanks for the reply.
Do you have a link to the recent changes? A PR maybe?

**Comment by monopsony** [comment]
Hey, I'm not exactly sure when those changes were pushed, but the root is essentially here: https://github.com/BigWigsMods/BigWigs/blob/master/Loader.lua#L1537 

When I initially created ElWigo, I relied on the BigWigsLoader to find bosses, their abilities and all other info to populate everything ElWigo needed to function (and most importantly to create its interface). Now, BigWigs requires an actual slash command to be called in order for the BigWigsLoader to be loaded. I need to look through the code to see if I can make everything but the ElWigo options (which requires a slash command to be opened anyways) independent of the BigWigsLoader without a) hardcoding raid/abilities information myself and b) rewriting too much of my code. Some of the info I need can surely be found in the BigWigs Core instead, I just need to find it.

**Comment by monopsony** [comment]
Hello again! 

I just pushed a new version that should work in TBC (works for me at least). It also has some old minor changes from months that I never bothered to commit so not all the changes are relevant. Either way, the workaround was not as bad as I thought (for once, I dont hate my past self) and it seemed to work for me now.

I'll leave this open still, just to make sure that stuff is actually working before I close this issue. On that note, I really appreciate you taking the time to try and fix my mistakes, but if my fix is working then I'll stick with it as I believe it's a bit less hacky. Thanks again!

**Comment by vendethiel** [comment]
> but if my fix is working then I'll stick with it as I believe it's a bit less hacky.

Definitely :). I just hacked at it until it worked, your fix looks much better.


Fixed by 3ace47debc4353e44fe0da4667411e3554374f26.

**Comment by vendethiel** [comment]
Thank you for taking the time to fix it even though you don't actively play!
