### ISSUE TITLE
WotLK Raid/Dungeon Info 

### ISSUE THREAD

**Issue by Fawenah** [monopsony/ElWigo#7]
With the new WotLK expansion, the new dungeons and raids are not getting loaded.

Updating the zone table with the new BW WotLK packages gives you the zones/bosses:
![image](https://user-images.githubusercontent.com/15831364/195796656-f05fde18-5166-4cd7-8166-0a4b5d8a0a99.png)

Options.lua, row 1596
`zoneTbl[k] == "BigWigs_Shadowlands" or
                zoneTbl[k] == "LittleWigs_Shadowlands" or
                zoneTbl[k] == "BigWigs_BurningCrusade" or
                zoneTbl[k] == "LittleWigs_BurningCrusade" or
                zoneTbl[k] == "BigWigs_WrathOfTheLichKing" or
                zoneTbl[k] == "LittleWigs_WrathOfTheLichKing"`

However it does not successfully load all options for raids and bosses.
It seems to struggle with some bosses, my first guess was due apostrophe (such as in Kel'Thuzad) and doesn't load him at all.
But Anub'Rekhan loads.
![image](https://user-images.githubusercontent.com/15831364/195798106-77c7c97c-5712-4f2d-bfcd-476f3f22bf27.png)

Most raids are unpopulated.
![image](https://user-images.githubusercontent.com/15831364/195798248-be7d0ccb-4247-47e5-9724-a2f81792be67.png)

I assume it's something in the refreshInfo where it fetches the BW info (?). But I haven't figured out why yet.

**Comment by monopsony** [comment]
2 years late because I stopped playing, but I don't seem to be able to reproduce this. Anyone can feel free to re-open if it's still happening though.
